### ISSUE TITLE
Перезапуск прграммы

### ISSUE THREAD

**Issue by myalinivan** [myalinivan/men-adventures#3]
Написать перезапуск программы с последнего шага после смерти персонажа.

**Comment by romansosnovsky** [comment]
Задача менее чем на 5 минут. Писать описание задачи - дольше.

**Comment by myalinivan** [comment]
Даже если по клику клавиши?

**Comment by romansosnovsky** [comment]
Непонял вопроса.

**Comment by myalinivan** [comment]
После нажатия любой клавиши программа переходит к тому шагу на котором была через n секунд
